# Generated by Django 5.0.7 on 2024-07-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genAI', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='newuser',
        ),
    ]
