# Generated by Django 5.0.7 on 2024-07-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genAI', '0002_rename_user_newuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='newuser',
            new_name='users',
        ),
    ]
